const GET_RECEPTIONS = 'GET_RECEPTIONS';
const GET_RECEPTIONS_SUCCESS = 'GET_RECEPTIONS_SUCCESS';
const GET_RECEPTIONS_ERROR = 'GET_RECEPTIONS_ERROR';
const ADD_RECEPTION = 'ADD_RECEPTION';
const ADD_RECEPTION_SUCCESS = 'ADD_RECEPTION_SUCCESS';
const ADD_RECEPTION_ERROR = 'ADD_RECEPTION_ERROR';

export { 
  GET_RECEPTIONS,
  GET_RECEPTIONS_SUCCESS,
  GET_RECEPTIONS_ERROR,
  ADD_RECEPTION,
  ADD_RECEPTION_SUCCESS,
  ADD_RECEPTION_ERROR
};