  const SEND_REGISTRATION_FORM = 'SEND_REGISTRATION_FORM';
  const SEND_REGISTRATION_FORM_SUCCESS = 'SEND_REGISTRATION_FORM_SUCCESS';
  const SEND_REGISTRATION_FORM_ERROR = 'SEND_REGISTRATION_FORM_ERROR'  

export { SEND_REGISTRATION_FORM, SEND_REGISTRATION_FORM_SUCCESS, SEND_REGISTRATION_FORM_ERROR };