const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION';
const SUBMIT_REGISTRATION_SUCCESS = 'SUBMIT_REGISTRATION_SUCCESS';
const SUBMIT_REGISTRATION_ERROR = 'SUBMIT_REGISTRATION_ERROR'
const SUBMIT_AUTHORIZATION = 'SUBMIT_AUTHORIZATION'
const SUBMIT_AUTHORIZATION_SUCCESS = 'SUBMIT_AUTHORIZATION_SUCCESS';
const SUBMIT_AUTHORIZATION_ERROR = 'SUBMIT_AUTHORIZATION_ERROR'
const GET_RECEPTIONS = 'GET_RECEPTIONS';
const GET_RECEPTIONS_SUCCESS = 'GET_RECEPTIONS_SUCCESS';
const GET_RECEPTIONS_ERROR = 'GET_RECEPTIONS_ERROR';
const ADD_RECEPTION = 'ADD_RECEPTION';
const ADD_RECEPTION_SUCCESS = 'ADD_RECEPTION_SUCCESS';
const ADD_RECEPTION_ERROR = 'ADD_RECEPTION_ERROR';

export { 
  SUBMIT_REGISTRATION, 
  SUBMIT_REGISTRATION_SUCCESS, 
  SUBMIT_REGISTRATION_ERROR,
  SUBMIT_AUTHORIZATION,
  SUBMIT_AUTHORIZATION_SUCCESS,
  SUBMIT_AUTHORIZATION_ERROR,
  GET_RECEPTIONS,
  GET_RECEPTIONS_SUCCESS,
  GET_RECEPTIONS_ERROR,
  ADD_RECEPTION,
  ADD_RECEPTION_SUCCESS,
  ADD_RECEPTION_ERROR
};