const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION';
const SUBMIT_REGISTRATION_SUCCESS = 'SUBMIT_REGISTRATION_SUCCESS';
const SUBMIT_REGISTRATION_ERROR = 'SUBMIT_REGISTRATION_ERROR'
const SUBMIT_AUTHORIZATION = 'SUBMIT_AUTHORIZATION'
const SUBMIT_AUTHORIZATION_SUCCESS = 'SUBMIT_AUTHORIZATION_SUCCESS';
const SUBMIT_AUTHORIZATION_ERROR = 'SUBMIT_AUTHORIZATION_ERROR'

export { 
  SUBMIT_REGISTRATION, 
  SUBMIT_REGISTRATION_SUCCESS, 
  SUBMIT_REGISTRATION_ERROR,
  SUBMIT_AUTHORIZATION,
  SUBMIT_AUTHORIZATION_SUCCESS,
  SUBMIT_AUTHORIZATION_ERROR
};